name: "Terraform AWS base plan"

# Trigger when the project builds successfully.
on:
  workflow_run:
    workflows: [Build and Publish Docker image]
    types: [completed]

defaults:
  run:
    working-directory: ./terraform/awsbase

jobs:
  terraform-plan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0

      # Provides AWS credentials to Terraform
      # By default, Terraform checks the home directory for a .aws folder with a credential file
      - name: "Setup - Build AWS Credentials"
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      # Downloads a specific version of Terraform CLI and adds it to PATH
      - name: "Setup - Terraform CLI"
        uses: hashicorp/setup-terraform@v3

      # Init pulls credentials from the .aws/credentials file by default
      - name: "Run - Terraform Init"
        run: terraform init -input=false

      - name: "Run - Terraform Plan"
        run: terraform plan -input=false -no-color